# Generated by Django 3.2.4 on 2023-10-18 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RP1',
        ),
        migrations.DeleteModel(
            name='RP10',
        ),
        migrations.DeleteModel(
            name='RP2',
        ),
        migrations.DeleteModel(
            name='RP3',
        ),
        migrations.DeleteModel(
            name='RP4',
        ),
        migrations.DeleteModel(
            name='RP5',
        ),
        migrations.DeleteModel(
            name='RP6',
        ),
        migrations.DeleteModel(
            name='RP7',
        ),
        migrations.DeleteModel(
            name='RP8',
        ),
        migrations.DeleteModel(
            name='RP9',
        ),
    ]
