# Generated by Django 3.2.4 on 2023-10-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('API', '0002_auto_20231018_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id_respuesta', models.AutoField(db_column='idRespuesta', primary_key=True, serialize=False)),
                ('frecuencia', models.CharField(db_column='frecuencia', max_length=50)),
                ('c_navegacion', models.CharField(db_column='c_navegacion', max_length=200)),
                ('tipo_producto', models.CharField(db_column='tipo_producto', max_length=50)),
                ('diseño', models.CharField(db_column='diseño', max_length=50)),
                ('colores', models.CharField(db_column='colores', max_length=50)),
                ('met_pago', models.CharField(db_column='met_pago', max_length=50)),
                ('dispositivo', models.CharField(db_column='dispositivo', max_length=50)),
                ('not_correo', models.CharField(db_column='not_correo', max_length=20)),
                ('factores', models.CharField(db_column='factores', max_length=100)),
                ('sug_mejoras', models.CharField(db_column='sug_mejoras', max_length=100)),
            ],
        ),
    ]
