# Generated by Django 3.2.4 on 2023-10-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_encuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='sug_mejoras',
            field=models.CharField(db_column='sug_mejoras', max_length=255),
        ),
    ]
