# Generated by Django 3.2.4 on 2023-10-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_encuesta_sug_mejoras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='id_respuesta',
            field=models.IntegerField(db_column='idRespuesta', primary_key=True, serialize=False),
        ),
    ]
