# Generated by Django 3.2.4 on 2023-10-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_encuesta_id_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='colores',
            field=models.CharField(db_column='colores', max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='diseño',
            field=models.CharField(db_column='diseño', max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='dispositivo',
            field=models.CharField(db_column='dispositivo', max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='frecuencia',
            field=models.CharField(db_column='frecuencia', max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='met_pago',
            field=models.CharField(db_column='met_pago', max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='not_correo',
            field=models.CharField(db_column='not_correo', max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='tipo_producto',
            field=models.CharField(db_column='tipo_producto', max_length=100),
        ),
    ]
