# Generated by Django 3.2.4 on 2023-10-25 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20231023_1741'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='encuesta',
            table='encuesta',
        ),
    ]
