# Generated by Django 3.2.4 on 2023-11-14 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
