# Generated by Django 3.2.4 on 2023-11-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrador'), ('client', 'Cliente')], max_length=20),
        ),
    ]
