# Generated by Django 3.2.4 on 2023-11-14 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='tipo_usuario',
        ),
    ]
