# Generated by Django 3.2.4 on 2023-11-14 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('API', '0012_auto_20231114_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
