# Generated by Django 3.2.23 on 2023-12-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_detalle_venta_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='id_venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='usuario_id',
        ),
        migrations.DeleteModel(
            name='Detalle_Venta',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
