# Generated by Django 3.2.23 on 2023-12-18 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0018_auto_20231218_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(db_column='id_producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('precio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=10)),
                ('cantidad_stock', models.IntegerField(db_column='cantidad_stock')),
                ('imagen', models.CharField(db_column='imagen', max_length=100)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.IntegerField(db_column='id_venta', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now=True, db_column='fecha')),
                ('usuario_id', models.ForeignKey(db_column='usuario_id', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.IntegerField(db_column='id_ticket', primary_key=True, serialize=False)),
                ('total', models.DecimalField(db_column='total', decimal_places=2, max_digits=10)),
                ('id_venta', models.ForeignKey(db_column='id_venta', default=1, on_delete=django.db.models.deletion.CASCADE, to='API.venta')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id_detalle_venta', models.IntegerField(db_column='id_detalle_venta', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='cantidad')),
                ('id_producto', models.ForeignKey(db_column='id_producto', default=1, on_delete=django.db.models.deletion.CASCADE, to='API.producto')),
                ('id_venta', models.ForeignKey(db_column='id_venta', default=1, on_delete=django.db.models.deletion.CASCADE, to='API.venta')),
            ],
            options={
                'db_table': 'detalle_venta',
            },
        ),
    ]
