# Generated by Django 3.2.23 on 2023-12-18 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0020_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='productos',
            field=models.ManyToManyField(through='API.Detalle_Venta', to='API.Producto'),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='API.producto'),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='id_venta',
            field=models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, to='API.venta'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id_venta',
            field=models.OneToOneField(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, to='API.venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario_id',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
