# Generated by Django 3.2.23 on 2023-12-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_auto_20231218_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(db_column='imagen', upload_to='static/productos/'),
        ),
    ]
