# Generated by Django 3.2.23 on 2023-12-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0023_alter_producto_id_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.IntegerField(db_column='id_producto', primary_key=True, serialize=False),
        ),
    ]
