# Generated by Django 3.2.23 on 2023-12-19 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_auto_20231219_1341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
