# Generated by Django 3.2.23 on 2023-12-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0029_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
