# Generated by Django 3.2.23 on 2023-12-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0037_auto_20231219_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.BigIntegerField(db_column='id_producto', primary_key=True, serialize=False),
        ),
    ]
