# Generated by Django 3.2.23 on 2023-12-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0050_auto_20231226_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_carrito',
            name='cantidad',
            field=models.IntegerField(db_column='cantidad', default=0),
        ),
    ]
