# Generated by Django 3.2.23 on 2023-12-30 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0055_auto_20231229_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_venta',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='detalle_venta',
            name='id_venta',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='id_venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='productos',
        ),
        migrations.DeleteModel(
            name='Detalle_Carrito',
        ),
        migrations.DeleteModel(
            name='Detalle_Venta',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
