# Generated by Django 3.2.23 on 2024-01-03 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0057_auto_20231229_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='id_venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='productos',
        ),
        migrations.DeleteModel(
            name='Detalle_Venta',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
