# Generated by Django 3.2.23 on 2024-01-03 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0059_auto_20240102_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='id_venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='productos',
        ),
        migrations.DeleteModel(
            name='Detalle_Venta',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
